- name: Playbook Ejemplo
  hosts: localhost
  gather_facts: true
  connection: local
  tags: always
  tasks:
    - shell: more /etc/hosts
      register: more_result
    - debug:
        msg: "{{ more_result }}"
    - shell: echo "La IP de {{ (more_result.stdout_lines | last).split(' ')[1] }} es {{ (more_result.stdout_lines | last).split(' ')[0] }}"    

