- name: Playbook Ejemplo
  hosts: test
  gather_facts: true
  connection: local
  tags: always
  tasks:
    - shell: more /etc/hosts

- name: Playbook Using Roles
  hosts: remote
  gather_facts: true
  tags: always
  pre_tasks:
    - shell: more /etc/hosts
  roles:
    - role: basic-setup
      machine_name: bigeekie-ansible
  post_tasks:
    - shell: more /etc/hosts

- name: Playbook Hostvars
  hosts: remote
  tags: always
  tasks:
    - debug:
        msg: "{{ hostvars[item].ansible_default_ipv4.address }}"
      with_items: "{{ groups.all }}"
