- name: Playbook Ejemplo
  hosts: test
  gather_facts: true
  connection: local
  tags: always
  tasks:
    - shell: more /etc/hosts

- name: Playbook Using Roles
  hosts: remote
  gather_facts: true
  tags: always
  tasks:
    - shell: echo "{{ inventory_hostname }}"
      register: machine_name_result
    - include_vars: "vault.yml"
    - include_role:
        name: basic-setup
      vars:
        machine_name: "{{ machine_name_result.stdout }}"
    - include_role:
        name: server
      vars:
        port: "{{ server.port }}"
    - shell: more /etc/hosts

- name: Playbook Hostvars
  hosts: remote
  tags: always
  tasks:
    - debug:
        msg: "{{ hostvars[item].ansible_default_ipv4.address }}"
      with_items: "{{ groups.all }}"
